# -*- coding: utf-8 -*-
"""LibPythonLS1_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1avKrtUCd-YzdUVIT1RUy7nVNkaV8JgAY
"""

# Задание 1
import pandas as pd
authors = pd.DataFrame({
    'author_id': [1, 2, 3],
    'author_name': ['Тургенев', 'Чехов', 'Островский'],
})
books = pd.DataFrame({
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price':[450, 300, 350, 500, 450, 370, 290]
})
print(authors)
print(books)

# Задание 2
authors_price = pd.merge(authors, books, on='author_id', how='outer')
print(authors_price)

# Задание 3
top5 = authors_price.nlargest(5, "price")
print(top5)

# Задание 4
groupby = authors_price.groupby("author_name")
authors_stat = groupby.agg(price_min=('price', 'min'), price_max=('price', 'max'), price_mean=('price', 'mean'))
print(authors_stat)

# Задание 5
df3 = pd.DataFrame(
    {'cover': ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']},
    index=[0, 1, 2, 3, 4, 5, 6]
)

import numpy as np
authors_price = pd.concat([authors_price, df3], axis=1)
authors_price
authors_price1  = pd.pivot_table(authors_price, index="author_name", columns="cover", values="price", aggfunc=[np.sum])
print(authors_price1)