# -*- coding: utf-8 -*-
"""LibPythonLS1_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15q19UrI2Us5dTwUzqp13OYDBO1rCUmDj
"""

##  Задание 1
import numpy as np
a = np.array([[1, 2, 3, 3, 1],
                [6, 8, 11, 10, 7]]).transpose()
mean_a = np.mean(ar1, axis = 1)
print(a)
print(mean_a)

## Задание 2
a_centered= a - mean_a
print(a_centered)

## Задание 3
a_centered_sp = np.dot( a_centered[:, 0], a_centered[:, 1])
print(a_centered_sp)
print(a_centered_sp / (len(a_centered[:, 0]) - 1))

## Задание 4
print(np.cov(a_centered.transpose()))