# -*- coding: utf-8 -*-
"""LibPythonLS3_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xIkd-tUJC12mgt-1F1Abs7ACcr_ptMbw
"""

# Commented out IPython magic to ensure Python compatibility.
# Задание 1
import numpy as np
from matplotlib import pyplot as plt
# %matplotlib inline
x = [1, 2, 3, 4, 5, 6, 7]
y = [3.5, 3.8, 4.2, 4.5, 5, 5.5, 7.]
plt.plot(x, y)
plt.show()
plt.scatter(x, y)
plt.show()

# Задание 2
t = np.linspace(0, 10, 51)
f = np.cos(x)
plt.plot(x, f, color="green")
plt.title("График f(t)")
plt.xlabel("Значения t")
plt.ylabel("Значения f")
plt.axis([0.5, 9.5, -2.5, 2.5])
plt.show()

# Задание 3
x = np.linspace(-3, 3, 51)
y1 = x**2
y2 = 2 * x + 0.5
y3 = -3 * x - 1.5
y4 = np.sin(x)
fig, ax = plt.subplots(nrows=2, ncols=2)
fig.set_size_inches(8, 6)
fig.subplots_adjust(wspace=0.3, hspace=0.3)
fig.suptitle("Графиуи y1-y4")
ax1, ax2, ax3, ax4 = ax.flatten()
ax1.plot(x, y1)
ax1.set_title("График y1")
ax1.set_xlim([-5, 5])
ax2.plot(x, y2)
ax2.set_title("График y2")
ax3.plot(x, y3)
ax3.set_title("График y3")
ax4.plot(x, y4)
ax4.set_title("График y4")

Задание 4

