# -*- coding: utf-8 -*-
"""LibPythonLS3_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QO29-Ye4QylhQnHQY7_mI3XSF6qnWBL5
"""

import numpy as np

# Задание 1
x =np.arange(12, 24)
print(x)

# Задание 2
x1= x.reshape(2, 6)
x2= x.reshape(6, 2)
x3= x.reshape(3, 4)
x4= x.reshape(4, 3)
x5= x.reshape(12, 1)
print(f'{x1} \n {x2} \n {x3} \n {x4} \n {x5}')

# Задание 3
# Задание 2
x1= x.reshape(2, -1)
x2= x.reshape(6, -1)
x3= x.reshape(3, -1)
x4= x.reshape(-1, 3)
x5= x.reshape(-1, 1)
print(f'{x1} \n {x2} \n {x3} \n {x4} \n {x5}')

# Задание 4
# Нет
print(x.shape)
print(x5.shape)

# Задание 5
a = np.random.normal(0, 1, (3,4))
af = a.flatten()
print(a)
print(af)

# Задание 6
b =np.arange(20, 0, -2)
print(b)

# Задание 7
# Разница в размерности массивов
c =np.arange(20, 0, -2).reshape(-1, 1)
print(c)
print(b.shape, c.shape)

# Задание 8
a = np.zeros((2, 2))
b = np.ones((3, 2))
c = np.vstack((a, b))
print(a)
print(b)
print(c)
print(c.size)

# Задание 9
A =np.arange(0, 12).reshape(4, 3)
At = A.transpose()
B = np.dot(A, At)
print(A)
print(At)
print(B)
print(B.size, B.shape)
print(f'Не получится, det = {np.linalg.det(B)}')

# Задание 10
np.random.seed(seed=42)

# Задание 11
c = np.random.randint(0, 16, 16)
print(c)

# Задание 12
C = c.reshape(4, -1)
D = B + 10* C
det_D = np.linalg.det(D)
rank_D = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)
print(C)
print(D)
print(det_D, rank_D)
print(D_inv)

# Задание 13
D_inv[np.where(D_inv > 0)] = 1
D_inv[np.where(D_inv < 0)] = 0
E = np.where(D_inv, B, C)
print(D_inv)
print(E)